import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from fpdf import FPDF
df = pd.read_csv(r"C:\Users\mukke\OneDrive\Desktop\git\PRODIGY_DS_04\sentiment_results.csv")
sentiment_counts = df['Sentiment'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Sentiment Distribution')
plt.savefig("sentiment_pie_chart.png")
plt.close()
pos_text = " ".join(df[df['Sentiment'] == 'Positive']['text'])
pos_wc = WordCloud(width=800, height=400, background_color='white').generate(pos_text)
plt.figure(figsize=(10, 5))
plt.imshow(pos_wc, interpolation='bilinear')
plt.axis("off")
plt.title("Positive Word Cloud")
plt.savefig("positive_wordcloud.png")
plt.close()
neg_text = " ".join(df[df['Sentiment'] == 'Negative']['Text'])
neg_wc = WordCloud(width=800, height=400, background_color='white').generate(neg_text)
plt.figure(figsize=(10, 5))
plt.imshow(neg_wc, interpolation='bilinear')
plt.axis("off")
plt.title("Negative Word Cloud")
plt.savefig("negative_wordcloud.png")
plt.close()
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", 'B', 16)
pdf.cell(0, 10, "Twitter Sentiment Analysis Report", ln=True, align='C')
pdf.set_font("Arial", '', 12)
pdf.multi_cell(0, 8, "This report summarizes the sentiment distribution of the analyzed tweets "
                     "and highlights the most common words in positive and negative sentiments.")
pdf.image("sentiment_pie_chart.png", x=30, w=150)
pdf.ln(10)
pdf.cell(0, 10, "Positive Word Cloud", ln=True, align='C')
pdf.image("positive_wordcloud.png", x=10, w=190)
pdf.ln(10)
pdf.cell(0, 10, "Negative Word Cloud", ln=True, align='C')
pdf.image("negative_wordcloud.png", x=10, w=190)
pdf.output("sentiment_analysis_report.pdf")
print("Report generated: sentiment_analysis_report.pdf")